// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	user "group-project-3/features/user"

	mock "github.com/stretchr/testify/mock"
)

// UserData is an autogenerated mock type for the UserDataInterface type
type UserData struct {
	mock.Mock
}

// DeleteOtherProfile provides a mock function with given fields: id
func (_m *UserData) DeleteOtherProfile(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: input, companyId
func (_m *UserData) Insert(input user.Core, companyId int) error {
	ret := _m.Called(input, companyId)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.Core, int) error); ok {
		r0 = rf(input, companyId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email, password
func (_m *UserData) Login(email string, password string) (user.Core, error) {
	ret := _m.Called(email, password)

	var r0 user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (user.Core, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) user.Core); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(user.Core)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectAll provides a mock function with given fields: pageNumber, pageSize, ManagerId, CompanyId
func (_m *UserData) SelectAll(pageNumber int, pageSize int, ManagerId int, CompanyId int) ([]user.Core, error) {
	ret := _m.Called(pageNumber, pageSize, ManagerId, CompanyId)

	var r0 []user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, int, int) ([]user.Core, error)); ok {
		return rf(pageNumber, pageSize, ManagerId, CompanyId)
	}
	if rf, ok := ret.Get(0).(func(int, int, int, int) []user.Core); ok {
		r0 = rf(pageNumber, pageSize, ManagerId, CompanyId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, int, int) error); ok {
		r1 = rf(pageNumber, pageSize, ManagerId, CompanyId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectOtherProfile provides a mock function with given fields: id
func (_m *UserData) SelectOtherProfile(id int) (user.Core, error) {
	ret := _m.Called(id)

	var r0 user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (user.Core, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) user.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Core)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectProfile provides a mock function with given fields: id
func (_m *UserData) SelectProfile(id int) (user.Core, error) {
	ret := _m.Called(id)

	var r0 user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (user.Core, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) user.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Core)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOtherProfile provides a mock function with given fields: id, input
func (_m *UserData) UpdateOtherProfile(id int, input user.UserDetailEntity) error {
	ret := _m.Called(id, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, user.UserDetailEntity) error); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfile provides a mock function with given fields: id, input
func (_m *UserData) UpdateProfile(id int, input user.UserDetailEntity) error {
	ret := _m.Called(id, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, user.UserDetailEntity) error); ok {
		r0 = rf(id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserData creates a new instance of UserData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserData(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserData {
	mock := &UserData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
